@param com.oakinvest.kiso.cli.model.util.PageMetadata pageMetadata

<!-- Favicons ====================================================================================================== -->
<link href="${pageMetadata.assetBasePath()}assets/favicon/kiso_favicon_light_16x16.svg"
      rel="icon" type="image/svg+xml">
<link href="${pageMetadata.assetBasePath()}assets/favicon/kiso_favicon_light_16x16.svg"
      media="(prefers-color-scheme: light)" rel="icon" sizes="16x16" type="image/svg+xml">
<link href="${pageMetadata.assetBasePath()}assets/favicon/kiso_favicon_dark_16x16.svg"
      media="(prefers-color-scheme: dark)" rel="icon" sizes="16x16" type="image/svg+xml">

<link href="${pageMetadata.assetBasePath()}assets/favicon/kiso_favicon_light_32x32.svg"
      rel="icon" type="image/svg+xml">
<link href="${pageMetadata.assetBasePath()}assets/favicon/kiso_favicon_light_32x32.svg"
      media="(prefers-color-scheme: light)" rel="icon" sizes="32x32" type="image/svg+xml">
<link href="${pageMetadata.assetBasePath()}assets/favicon/kiso_favicon_dark_32x32.svg"
      media="(prefers-color-scheme: dark)" rel="icon" sizes="32x32" type="image/svg+xml">

<link href="${pageMetadata.assetBasePath()}assets/favicon/kiso_favicon_light_180x180.svg"
      rel="apple-touch-icon" sizes="180x180">
<link href="${pageMetadata.assetBasePath()}assets/favicon/kiso_favicon_dark_180x180.svg"
      rel="apple-touch-icon" sizes="180x180">
