package com.oakinvest.kiso.core.util.contants;

import lombok.experimental.UtilityClass;

/**
 * Frontmatter constants.
 */
@UtilityClass
@SuppressWarnings({"checkstyle:HideUtilityClassConstructor"})
public class FrontmatterConstants {

    /** Frontmatter delimiter. */
    public static final String FRONTMATTER_DELIMITER = "---";

    /** Frontmatter OKF version key. */
    public static final String OKF_VERSION_KEY = "okf_version";

    /** Frontmatter key for type. */
    public static final String TYPE_KEY = "type";

    /** Frontmatter key for title. */
    public static final String TITLE_KEY = "title";

    /** Frontmatter key for description. */
    public static final String DESCRIPTION_KEY = "description";

    /** Frontmatter key for resource. */
    public static final String RESOURCE_KEY = "resource";

    /** Frontmatter key for tags. */
    public static final String TAGS_KEY = "tags";

    /** Frontmatter key for timestamp. */
    public static final String TIMESTAMP_KEY = "timestamp";

    /** Frontmatter key for generated metadata. */
    public static final String GENERATED_KEY = "generated";

    /** Frontmatter key for generated by metadata. */
    public static final String GENERATED_BY_KEY = "by";

    /** Frontmatter key for generated at metadata. */
    public static final String GENERATED_AT_KEY = "at";

    /** Frontmatter key for source metadata. */
    public static final String SOURCES_KEY = "sources";

    /** Frontmatter key for source id metadata. */
    public static final String SOURCE_ID_KEY = "id";

    /** Frontmatter key for source title metadata. */
    public static final String SOURCE_TITLE_KEY = "title";

    /** Frontmatter key for source author metadata. */
    public static final String SOURCE_AUTHOR_KEY = "author";

    /** Frontmatter key for source usage count metadata. */
    public static final String SOURCE_USAGE_COUNT_KEY = "usage_count";

    /** Frontmatter key for source last modified metadata. */
    public static final String SOURCE_LAST_MODIFIED_KEY = "last_modified";

    /** Frontmatter key for usage window metadata. */
    public static final String USAGE_WINDOW_KEY = "usage_window";

    /** Frontmatter key for usage window start metadata. */
    public static final String USAGE_WINDOW_FROM_KEY = "from";

    /** Frontmatter key for usage window end metadata. */
    public static final String USAGE_WINDOW_TO_KEY = "to";

    /** Frontmatter key for verified metadata. */
    public static final String VERIFIED_KEY = "verified";

    /** Frontmatter key for status metadata. */
    public static final String STATUS_KEY = "status";

    /** Frontmatter key for stale after metadata. */
    public static final String STALE_AFTER_KEY = "stale_after";

    /** Frontmatter key for computation runtime metadata. */
    public static final String RUNTIME_KEY = "runtime";

    /** Frontmatter key for computation parameters metadata. */
    public static final String PARAMETERS_KEY = "parameters";

    /** Frontmatter key for computation parameter name metadata. */
    public static final String PARAMETER_NAME_KEY = "name";

    /** Frontmatter key for computation parameter type metadata. */
    public static final String PARAMETER_TYPE_KEY = "type";

    /** Frontmatter key for computation parameter required metadata. */
    public static final String PARAMETER_REQUIRED_KEY = "required";

    /** Frontmatter key for computation file metadata. */
    public static final String COMPUTATION_KEY = "computation";

    /** Frontmatter key for computation executor metadata. */
    public static final String EXECUTOR_KEY = "executor";

    /** Frontmatter key for computation executor receipt metadata. */
    public static final String EXECUTOR_RECEIPT_KEY = "receipt";

    /** Frontmatter key for computation attester metadata. */
    public static final String ATTESTER_KEY = "attester";

}
