<?xml version="1.0" encoding="UTF-8"?>
<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xmlns="http://maven.apache.org/POM/4.0.0"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <!-- Parent ==================================================================================================== -->
    <parent>
        <groupId>com.oakinvest.kiso</groupId>
        <artifactId>kiso</artifactId>
        <version>0.1.5-SNAPSHOT</version>
        <relativePath>../../pom.xml</relativePath>
    </parent>

    <!-- Project information ======================================================================================= -->
    <artifactId>kiso-core</artifactId>
    <packaging>jar</packaging>
    <name>Kiso core</name>
    <description>Common libraries.</description>

    <!-- Dependencies ============================================================================================== -->
    <dependencies>
        <!-- Main libraries -->
        <dependency>
            <groupId>org.commonmark</groupId>
            <artifactId>commonmark</artifactId>
        </dependency>
        <dependency>
            <groupId>org.commonmark</groupId>
            <artifactId>commonmark-ext-autolink</artifactId>
        </dependency>
        <dependency>
            <groupId>org.commonmark</groupId>
            <artifactId>commonmark-ext-gfm-tables</artifactId>
        </dependency>
        <dependency>
            <groupId>gg.jte</groupId>
            <artifactId>jte</artifactId>
        </dependency>

        <!-- Boilerplate and utils -->
        <dependency>
            <groupId>org.jspecify</groupId>
            <artifactId>jspecify</artifactId>
        </dependency>
        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>org.apache.commons</groupId>
            <artifactId>commons-lang3</artifactId>
        </dependency>
        <dependency>
            <groupId>commons-io</groupId>
            <artifactId>commons-io</artifactId>
        </dependency>
        <dependency>
            <groupId>org.apache.commons</groupId>
            <artifactId>commons-text</artifactId>
        </dependency>

        <!-- Test dependencies -->
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.assertj</groupId>
            <artifactId>assertj-core</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.jsoup</groupId>
            <artifactId>jsoup</artifactId>
        </dependency>
    </dependencies>

    <!-- Build configuration ======================================================================================= -->
    <build>
        <plugins>
            <!-- JTE templates ===================================================================================== -->
            <plugin>
                <groupId>gg.jte</groupId>
                <artifactId>jte-maven-plugin</artifactId>
                <version>${jte.version}</version>
                <configuration>
                    <sourceDirectory>${project.basedir}/src/main/jte</sourceDirectory>
                    <targetDirectory>${project.build.outputDirectory}</targetDirectory>
                    <contentType>Html</contentType>
                </configuration>
                <executions>
                    <execution>
                        <goals>
                            <goal>precompile</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>

            <!-- Frontend dependencies ============================================================================= -->
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-dependency-plugin</artifactId>
                <version>${maven.dependency.plugin.version}</version>
                <executions>
                    <execution>
                        <id>unpack-webjar-assets</id>
                        <phase>generate-resources</phase>
                        <goals>
                            <goal>unpack</goal>
                        </goals>
                        <configuration>
                            <artifactItems>
                                <artifactItem>
                                    <groupId>org.webjars.npm</groupId>
                                    <artifactId>daisyui</artifactId>
                                    <version>${daisyui.webjar.version}</version>
                                    <outputDirectory>${project.build.directory}/generated-webjar-assets/daisyui
                                    </outputDirectory>
                                    <includes>
                                        META-INF/resources/webjars/daisyui/${daisyui.webjar.version}/daisyui.css,
                                        META-INF/resources/webjars/daisyui/${daisyui.webjar.version}/themes.css
                                    </includes>
                                </artifactItem>
                                <artifactItem>
                                    <groupId>org.webjars.npm</groupId>
                                    <artifactId>tailwindcss__browser</artifactId>
                                    <version>${tailwindcss.webjar.version}</version>
                                    <outputDirectory>
                                        ${project.build.directory}/generated-webjar-assets/tailwindcss-browser
                                    </outputDirectory>
                                    <includes>
                                        META-INF/resources/webjars/tailwindcss__browser/${tailwindcss.webjar.version}/dist/index.global.js
                                    </includes>
                                </artifactItem>
                            </artifactItems>
                        </configuration>
                    </execution>
                </executions>
            </plugin>

            <!-- Assets ============================================================================================ -->
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-resources-plugin</artifactId>
                <version>${maven.resources.plugin.version}</version>
                <executions>
                    <execution>
                        <id>copy-assets</id>
                        <phase>process-resources</phase>
                        <goals>
                            <goal>copy-resources</goal>
                        </goals>
                        <configuration>
                            <outputDirectory>${project.build.outputDirectory}/assets</outputDirectory>
                            <resources>
                                <resource>
                                    <directory>${project.basedir}/src/main/jte/assets</directory>
                                    <excludes>
                                        <exclude>css/daisyui.css</exclude>
                                        <exclude>css/themes.css</exclude>
                                        <exclude>js/browser.js</exclude>
                                    </excludes>
                                </resource>
                                <resource>
                                    <directory>
                                        ${project.build.directory}/generated-webjar-assets/daisyui/META-INF/resources/webjars/daisyui/${daisyui.webjar.version}
                                    </directory>
                                    <targetPath>css</targetPath>
                                    <includes>
                                        <include>daisyui.css</include>
                                        <include>themes.css</include>
                                    </includes>
                                </resource>
                            </resources>
                        </configuration>
                    </execution>
                    <execution>
                        <id>copy-test-assets</id>
                        <phase>process-test-resources</phase>
                        <goals>
                            <goal>copy-resources</goal>
                        </goals>
                        <configuration>
                            <outputDirectory>${project.build.directory}/assets</outputDirectory>
                            <resources>
                                <resource>
                                    <directory>${project.basedir}/src/main/jte/assets</directory>
                                    <excludes>
                                        <exclude>css/daisyui.css</exclude>
                                        <exclude>css/themes.css</exclude>
                                        <exclude>js/browser.js</exclude>
                                    </excludes>
                                </resource>
                                <resource>
                                    <directory>
                                        ${project.build.directory}/generated-webjar-assets/daisyui/META-INF/resources/webjars/daisyui/${daisyui.webjar.version}
                                    </directory>
                                    <targetPath>css</targetPath>
                                    <includes>
                                        <include>daisyui.css</include>
                                        <include>themes.css</include>
                                    </includes>
                                </resource>
                            </resources>
                        </configuration>
                    </execution>
                </executions>
            </plugin>

            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-antrun-plugin</artifactId>
                <version>${maven.antrun.plugin.version}</version>
                <executions>
                    <execution>
                        <id>copy-tailwind-browser-asset</id>
                        <phase>process-resources</phase>
                        <goals>
                            <goal>run</goal>
                        </goals>
                        <configuration>
                            <target>
                                <copy
                                        file="${project.build.directory}/generated-webjar-assets/tailwindcss-browser/META-INF/resources/webjars/tailwindcss__browser/${tailwindcss.webjar.version}/dist/index.global.js"
                                        tofile="${project.build.outputDirectory}/assets/js/browser.js"/>
                            </target>
                        </configuration>
                    </execution>
                    <execution>
                        <id>copy-tailwind-browser-test-asset</id>
                        <phase>process-test-resources</phase>
                        <goals>
                            <goal>run</goal>
                        </goals>
                        <configuration>
                            <target>
                                <copy
                                        file="${project.build.directory}/generated-webjar-assets/tailwindcss-browser/META-INF/resources/webjars/tailwindcss__browser/${tailwindcss.webjar.version}/dist/index.global.js"
                                        tofile="${project.build.directory}/assets/js/browser.js"/>
                            </target>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>

</project>
