version: 2
updates:

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: "cron"
      # First Sunday of each month at 20:30.
      cronjob: "30 20 * * sun#1"
      timezone: "Europe/Paris"
    target-branch: development

  - package-ecosystem: maven
    directory: "/"
    schedule:
      interval: "cron"
      # First Sunday of each month at 20:30.
      cronjob: "30 20 * * sun#1"
      timezone: "Europe/Paris"
    target-branch: development
