package com.oakinvest.kiso.core.util;

import lombok.experimental.UtilityClass;

/**
 * Frontmatter constants.
 */
@UtilityClass
@SuppressWarnings({"checkstyle:HideUtilityClassConstructor"})
public class FrontmatterConstants {

    /** Frontmatter delimiter. */
    public static final String FRONTMATTER_DELIMITER = "---";

    /** Frontmatter key for type. */
    public static final String TYPE_KEY = "type";

    /** Frontmatter key for title. */
    public static final String TITLE_KEY = "title";

    /** Frontmatter key for description. */
    public static final String DESCRIPTION_KEY = "description";

    /** Frontmatter key for resource. */
    public static final String RESOURCE_KEY = "resource";

    /** Frontmatter key for tags. */
    public static final String TAGS_KEY = "tags";

    /** Frontmatter key for timestamp. */
    public static final String TIMESTAMP_KEY = "timestamp";

    /** Frontmatter key for generated metadata. */
    public static final String GENERATED_KEY = "generated";

    /** Frontmatter key for generated by metadata. */
    public static final String GENERATED_BY_KEY = "by";

    /** Frontmatter key for generated at metadata. */
    public static final String GENERATED_AT_KEY = "at";

}
