<?xml version="1.0" encoding="UTF-8"?>
<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xmlns="http://maven.apache.org/POM/4.0.0"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <!-- Parent ==================================================================================================== -->
    <parent>
        <groupId>com.oakinvest.kiso</groupId>
        <artifactId>kiso</artifactId>
        <version>0.2.4-SNAPSHOT</version>
        <relativePath>../../pom.xml</relativePath>
    </parent>

    <!-- Project information ======================================================================================= -->
    <artifactId>kiso-cli</artifactId>
    <packaging>jar</packaging>
    <name>Kiso cli</name>
    <description>Kiso cli is a publishing engine for Open Knowledge Format (OKF).</description>

    <!-- Project configuration ===================================================================================== -->
    <properties>
        <application.main.class>com.oakinvest.kiso.cli.Application</application.main.class>
    </properties>

    <!-- Dependencies ============================================================================================== -->
    <dependencies>
        <!-- Main libraries -->
        <dependency>
            <groupId>com.oakinvest.kiso</groupId>
            <artifactId>kiso-core</artifactId>
        </dependency>
        <dependency>
            <groupId>info.picocli</groupId>
            <artifactId>picocli</artifactId>
        </dependency>
        <dependency>
            <groupId>gg.jte</groupId>
            <artifactId>jte</artifactId>
        </dependency>

        <!-- Boilerplate and utils -->
        <dependency>
            <groupId>org.jspecify</groupId>
            <artifactId>jspecify</artifactId>
        </dependency>
        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-databind</artifactId>
        </dependency>
        <dependency>
            <groupId>com.fasterxml.jackson.dataformat</groupId>
            <artifactId>jackson-dataformat-yaml</artifactId>
        </dependency>
        <dependency>
            <groupId>net.lingala.zip4j</groupId>
            <artifactId>zip4j</artifactId>
        </dependency>

        <!-- HTML sanitization -->
        <dependency>
            <groupId>org.jsoup</groupId>
            <artifactId>jsoup</artifactId>
        </dependency>
        <dependency>
            <groupId>com.github.hazendaz</groupId>
            <artifactId>htmlcompressor</artifactId>
        </dependency>

        <!-- Test dependencies -->
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.assertj</groupId>
            <artifactId>assertj-core</artifactId>
            <scope>test</scope>
        </dependency>
    </dependencies>

    <!-- Build configuration ======================================================================================= -->
    <build>
        <plugins>
            <!-- Picocli annotation processing ===================================================================== -->
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <executions>
                    <execution>
                        <id>default-compile</id>
                        <configuration>
                            <annotationProcessorPaths>
                                <path>
                                    <groupId>info.picocli</groupId>
                                    <artifactId>picocli-codegen</artifactId>
                                    <version>${picocli.version}</version>
                                </path>
                                <path>
                                    <groupId>org.projectlombok</groupId>
                                    <artifactId>lombok</artifactId>
                                    <version>${lombok.version}</version>
                                </path>
                            </annotationProcessorPaths>
                        </configuration>
                    </execution>
                </executions>
            </plugin>

            <!-- Application execution ============================================================================= -->
            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>exec-maven-plugin</artifactId>
                <version>${maven.exec.plugin.version}</version>
            </plugin>

            <!-- JTE templates ===================================================================================== -->
            <plugin>
                <groupId>gg.jte</groupId>
                <artifactId>jte-maven-plugin</artifactId>
                <version>${jte.version}</version>
                <configuration>
                    <sourceDirectory>${project.basedir}/src/main/jte</sourceDirectory>
                    <targetDirectory>${project.build.outputDirectory}</targetDirectory>
                    <contentType>Html</contentType>
                </configuration>
                <executions>
                    <execution>
                        <goals>
                            <goal>precompile</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>

            <!-- Frontend dependencies ============================================================================= -->
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-dependency-plugin</artifactId>
                <version>${maven.dependency.plugin.version}</version>
                <executions>
                    <execution>
                        <id>unpack-webjar-assets</id>
                        <phase>generate-resources</phase>
                        <goals>
                            <goal>unpack</goal>
                        </goals>
                        <configuration>
                            <artifactItems>
                                <!-- DaisyUI ======================================================================= -->
                                <artifactItem>
                                    <groupId>org.webjars.npm</groupId>
                                    <artifactId>daisyui</artifactId>
                                    <version>${daisyui.webjar.version}</version>
                                    <outputDirectory>${project.build.directory}/generated-webjar-assets/daisyui
                                    </outputDirectory>
                                    <includes>
                                        META-INF/resources/webjars/daisyui/${daisyui.webjar.version}/daisyui.css,
                                        META-INF/resources/webjars/daisyui/${daisyui.webjar.version}/themes.css
                                    </includes>
                                </artifactItem>
                                <!-- TailwindCSS =================================================================== -->
                                <artifactItem>
                                    <groupId>org.webjars.npm</groupId>
                                    <artifactId>tailwindcss__browser</artifactId>
                                    <version>${tailwindcss.webjar.version}</version>
                                    <outputDirectory>
                                        ${project.build.directory}/generated-webjar-assets/tailwindcss-browser
                                    </outputDirectory>
                                    <includes>
                                        META-INF/resources/webjars/tailwindcss__browser/${tailwindcss.webjar.version}/dist/index.global.js
                                    </includes>
                                </artifactItem>
                                <!-- Minisearch ==================================================================== -->
                                <artifactItem>
                                    <groupId>org.webjars.npm</groupId>
                                    <artifactId>minisearch</artifactId>
                                    <version>${minisearch.webjar.version}</version>
                                    <outputDirectory>
                                        ${project.build.directory}/generated-webjar-assets/minisearch
                                    </outputDirectory>
                                    <includes>
                                        META-INF/resources/webjars/minisearch/${minisearch.webjar.version}/dist/umd/index.js
                                    </includes>
                                </artifactItem>
                                <!-- I18next ====================================================================== -->
                                <artifactItem>
                                    <groupId>org.webjars.npm</groupId>
                                    <artifactId>i18next</artifactId>
                                    <version>${i18next.webjar.version}</version>
                                    <outputDirectory>
                                        ${project.build.directory}/generated-webjar-assets/i18next
                                    </outputDirectory>
                                    <includes>
                                        META-INF/resources/webjars/i18next/${i18next.webjar.version}/dist/umd/i18next.js
                                    </includes>
                                </artifactItem>
                            </artifactItems>
                        </configuration>
                    </execution>
                </executions>
            </plugin>

            <!-- Assets ============================================================================================ -->
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-resources-plugin</artifactId>
                <version>${maven.resources.plugin.version}</version>
                <configuration>
                    <propertiesEncoding>${project.build.sourceEncoding}</propertiesEncoding>
                    <useDefaultDelimiters>false</useDefaultDelimiters>
                    <delimiters>
                        <delimiter>@</delimiter>
                    </delimiters>
                </configuration>
                <executions>
                    <execution>
                        <id>copy-assets</id>
                        <phase>process-resources</phase>
                        <goals>
                            <goal>copy-resources</goal>
                        </goals>
                        <configuration>
                            <outputDirectory>${project.build.outputDirectory}/assets</outputDirectory>
                            <resources>
                                <resource>
                                    <directory>${project.basedir}/src/main/jte/assets</directory>
                                    <excludes>
                                        <exclude>css/daisyui.css</exclude>
                                        <exclude>css/themes.css</exclude>
                                        <exclude>js/browser.js</exclude>
                                        <exclude>js/minisearch.js</exclude>
                                        <exclude>js/i18next.js</exclude>
                                    </excludes>
                                </resource>
                                <resource>
                                    <directory>
                                        ${project.build.directory}/generated-webjar-assets/daisyui/META-INF/resources/webjars/daisyui/${daisyui.webjar.version}
                                    </directory>
                                    <targetPath>css</targetPath>
                                    <includes>
                                        <include>daisyui.css</include>
                                        <include>themes.css</include>
                                    </includes>
                                </resource>
                            </resources>
                        </configuration>
                    </execution>
                    <execution>
                        <id>copy-test-assets</id>
                        <phase>process-test-resources</phase>
                        <goals>
                            <goal>copy-resources</goal>
                        </goals>
                        <configuration>
                            <outputDirectory>${project.build.directory}/assets</outputDirectory>
                            <resources>
                                <resource>
                                    <directory>${project.basedir}/src/main/jte/assets</directory>
                                    <excludes>
                                        <exclude>css/daisyui.css</exclude>
                                        <exclude>css/themes.css</exclude>
                                        <exclude>js/browser.js</exclude>
                                        <exclude>js/minisearch.js</exclude>
                                        <exclude>js/i18next.js</exclude>
                                    </excludes>
                                </resource>
                                <resource>
                                    <directory>
                                        ${project.build.directory}/generated-webjar-assets/daisyui/META-INF/resources/webjars/daisyui/${daisyui.webjar.version}
                                    </directory>
                                    <targetPath>css</targetPath>
                                    <includes>
                                        <include>daisyui.css</include>
                                        <include>themes.css</include>
                                    </includes>
                                </resource>
                            </resources>
                        </configuration>
                    </execution>
                </executions>
            </plugin>

            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-antrun-plugin</artifactId>
                <version>${maven.antrun.plugin.version}</version>
                <executions>
                    <execution>
                        <id>copy-js-asset</id>
                        <phase>process-resources</phase>
                        <goals>
                            <goal>run</goal>
                        </goals>
                        <configuration>
                            <target>
                                <copy failonerror="true"
                                      file="${project.build.directory}/generated-webjar-assets/tailwindcss-browser/META-INF/resources/webjars/tailwindcss__browser/${tailwindcss.webjar.version}/dist/index.global.js"
                                      tofile="${project.build.outputDirectory}/assets/js/browser.js"/>
                                <copy failonerror="true"
                                      file="${project.build.directory}/generated-webjar-assets/minisearch/META-INF/resources/webjars/minisearch/${minisearch.webjar.version}/dist/umd/index.js"
                                      tofile="${project.build.outputDirectory}/assets/js/minisearch.js"/>
                                <copy failonerror="true"
                                      file="${project.build.directory}/generated-webjar-assets/i18next/META-INF/resources/webjars/i18next/${i18next.webjar.version}/dist/umd/i18next.js"
                                      tofile="${project.build.outputDirectory}/assets/js/i18next.js"/>
                            </target>
                        </configuration>
                    </execution>
                    <execution>
                        <id>copy-js-test-asset</id>
                        <phase>process-test-resources</phase>
                        <goals>
                            <goal>run</goal>
                        </goals>
                        <configuration>
                            <target>
                                <copy
                                        file="${project.build.directory}/generated-webjar-assets/tailwindcss-browser/META-INF/resources/webjars/tailwindcss__browser/${tailwindcss.webjar.version}/dist/index.global.js"
                                        tofile="${project.build.directory}/assets/js/browser.js"/>
                                <copy
                                        file="${project.build.directory}/generated-webjar-assets/minisearch/META-INF/resources/webjars/minisearch/${minisearch.webjar.version}/dist/umd/index.js"
                                        tofile="${project.build.directory}/assets/js/minisearch.js"/>
                                <copy
                                        file="${project.build.directory}/generated-webjar-assets/i18next/META-INF/resources/webjars/i18next/${i18next.webjar.version}/dist/umd/i18next.js"
                                        tofile="${project.build.directory}/assets/js/i18next.js"/>
                            </target>
                        </configuration>
                    </execution>
                </executions>
            </plugin>

            <!-- Executable Java archive =========================================================================== -->
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-shade-plugin</artifactId>
                <version>${maven.shade.plugin.version}</version>
                <executions>
                    <execution>
                        <phase>package</phase>
                        <goals>
                            <goal>shade</goal>
                        </goals>
                        <configuration>
                            <createDependencyReducedPom>false</createDependencyReducedPom>
                            <shadedArtifactAttached>true</shadedArtifactAttached>
                            <shadedClassifierName>executable</shadedClassifierName>
                            <filters>
                                <filter>
                                    <artifact>*:*</artifact>
                                    <excludes>
                                        <exclude>module-info.class</exclude>
                                        <exclude>META-INF/MANIFEST.MF</exclude>
                                        <exclude>META-INF/versions/**/module-info.class</exclude>
                                    </excludes>
                                </filter>
                            </filters>
                            <transformers>
                                <transformer
                                        implementation="org.apache.maven.plugins.shade.resource.ServicesResourceTransformer"/>
                                <transformer
                                        implementation="org.apache.maven.plugins.shade.resource.AppendingTransformer">
                                    <resource>META-INF/LICENSE</resource>
                                </transformer>
                                <transformer
                                        implementation="org.apache.maven.plugins.shade.resource.AppendingTransformer">
                                    <resource>META-INF/LICENSE.txt</resource>
                                </transformer>
                                <transformer
                                        implementation="org.apache.maven.plugins.shade.resource.AppendingTransformer">
                                    <resource>META-INF/NOTICE</resource>
                                </transformer>
                                <transformer
                                        implementation="org.apache.maven.plugins.shade.resource.AppendingTransformer">
                                    <resource>META-INF/NOTICE.txt</resource>
                                </transformer>
                                <transformer
                                        implementation="org.apache.maven.plugins.shade.resource.AppendingTransformer">
                                    <resource>license/LICENSE</resource>
                                </transformer>
                                <transformer
                                        implementation="org.apache.maven.plugins.shade.resource.AppendingTransformer">
                                    <resource>license/LICENSE.dom-documentation.txt</resource>
                                </transformer>
                                <transformer
                                        implementation="org.apache.maven.plugins.shade.resource.AppendingTransformer">
                                    <resource>license/LICENSE.dom-software.txt</resource>
                                </transformer>
                                <transformer
                                        implementation="org.apache.maven.plugins.shade.resource.AppendingTransformer">
                                    <resource>license/NOTICE</resource>
                                </transformer>
                                <transformer
                                        implementation="org.apache.maven.plugins.shade.resource.AppendingTransformer">
                                    <resource>license/README.dom.txt</resource>
                                </transformer>
                                <transformer
                                        implementation="org.apache.maven.plugins.shade.resource.ManifestResourceTransformer">
                                    <mainClass>${application.main.class}</mainClass>
                                </transformer>
                            </transformers>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>

        <!-- Resource filtering - Used to set version in src/main/resources/version.properties ===================== -->
        <resources>
            <resource>
                <directory>src/main/resources</directory>
                <filtering>true</filtering>
            </resource>
        </resources>

    </build>

    <!-- Native build configuration ================================================================================= -->
    <profiles>
        <profile>
            <id>native</id>
            <build>
                <plugins>
                    <!--suppress MavenModelInspection -->
                    <plugin>
                        <groupId>org.graalvm.buildtools</groupId>
                        <artifactId>native-maven-plugin</artifactId>
                        <version>${maven.graalvm.native.plugin.version}</version>
                        <configuration>
                            <imageName>kiso-cli</imageName>
                            <mainClass>${application.main.class}</mainClass>
                            <fallback>false</fallback>
                        </configuration>
                        <dependencies>
                            <dependency>
                                <groupId>org.apache.maven.shared</groupId>
                                <artifactId>maven-shared-utils</artifactId>
                                <version>${maven.shared.utils.version}</version>
                            </dependency>
                        </dependencies>
                    </plugin>
                </plugins>
            </build>
        </profile>
    </profiles>

</project>
