package com.oakinvest.kiso.core.validation;

import com.oakinvest.kiso.core.BaseTest;
import com.oakinvest.kiso.core.model.markdown.Actor;
import com.oakinvest.kiso.core.model.markdown.Frontmatter;
import com.oakinvest.kiso.core.model.markdown.trust.TrustEvent;
import com.oakinvest.kiso.core.validation.rule.TrustEventRule;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

import java.nio.file.Path;
import java.util.List;

import static com.oakinvest.kiso.core.util.types.MarkdownFileKind.CONCEPT;
import static com.oakinvest.kiso.core.validation.ValidationCode.INVALID_GENERATED_AT;
import static com.oakinvest.kiso.core.validation.ValidationCode.INVALID_VERIFIED_AT;
import static com.oakinvest.kiso.core.validation.ValidationCode.MISSING_GENERATED_AT;
import static com.oakinvest.kiso.core.validation.ValidationCode.MISSING_GENERATED_BY;
import static com.oakinvest.kiso.core.validation.ValidationCode.MISSING_VERIFIED_AT;
import static com.oakinvest.kiso.core.validation.ValidationCode.MISSING_VERIFIED_BY;
import static com.oakinvest.kiso.core.validation.ValidationSeverity.ERROR;
import static org.assertj.core.api.Assertions.assertThat;

@DisplayName("Trust event rule")
public class TrustEventRuleTest extends BaseTest {

    final TrustEventRule rule = new TrustEventRule();

    @Test
    @DisplayName("Accept valid generated and verified trust events")
    void validTrustEvents() {
        var markdownFilePath = Path.of("concept-with-valid-trust-events.md");
        var frontmatter = Frontmatter.builder()
                .type("Concept")
                .generated(TrustEvent.builder()
                        .by(Actor.of("reference_agent/gemini-2.5-pro"))
                        .at("2026-06-20T22:53:05Z")
                        .build())
                .verified(List.of(TrustEvent.builder()
                        .by(Actor.of("human:straumat"))
                        .at("2026-06-25T09:00:00Z")
                        .build()))
                .build();
        var markdownFile = createMarkdownFile(markdownFilePath, CONCEPT, frontmatter);

        assertThat(rule.validate(createKnowledgeBundleWith(markdownFile), markdownFile)).isEmpty();
    }

    @Test
    @DisplayName("Report missing generated by")
    void missingGeneratedBy() {
        var markdownFilePath = Path.of("concept-without-generated-by.md");
        var frontmatter = Frontmatter.builder()
                .type("Concept")
                .generated(TrustEvent.builder()
                        .at("2026-06-20T22:53:05Z")
                        .build())
                .build();
        var markdownFile = createMarkdownFile(markdownFilePath, CONCEPT, frontmatter);

        assertThat(rule.validate(createKnowledgeBundleWith(markdownFile), markdownFile)).satisfiesOnlyOnce(issue -> {
            assertThat(issue.severity()).isEqualTo(ERROR);
            assertThat(issue.code()).isEqualTo(MISSING_GENERATED_BY);
            assertThat(issue.message()).isEqualTo("Missing generated.by field in frontmatter");
            assertThat(issue.path()).isEqualTo(markdownFilePath);
        });
    }

    @Test
    @DisplayName("Report missing generated at")
    void missingGeneratedAt() {
        var markdownFilePath = Path.of("concept-without-generated-at.md");
        var frontmatter = Frontmatter.builder()
                .type("Concept")
                .generated(TrustEvent.builder()
                        .by(Actor.of("reference_agent/gemini-2.5-pro"))
                        .build())
                .build();
        var markdownFile = createMarkdownFile(markdownFilePath, CONCEPT, frontmatter);

        assertThat(rule.validate(createKnowledgeBundleWith(markdownFile), markdownFile)).satisfiesOnlyOnce(issue -> {
            assertThat(issue.severity()).isEqualTo(ERROR);
            assertThat(issue.code()).isEqualTo(MISSING_GENERATED_AT);
            assertThat(issue.message()).isEqualTo("Missing generated.at field in frontmatter");
            assertThat(issue.path()).isEqualTo(markdownFilePath);
        });
    }

    @Test
    @DisplayName("Report invalid generated at")
    void invalidGeneratedAt() {
        var markdownFilePath = Path.of("concept-with-invalid-generated-at.md");
        var frontmatter = Frontmatter.builder()
                .type("Concept")
                .generated(TrustEvent.builder()
                        .by(Actor.of("reference_agent/gemini-2.5-pro"))
                        .at("20-06-2026T22:53:05Z")
                        .build())
                .build();
        var markdownFile = createMarkdownFile(markdownFilePath, CONCEPT, frontmatter);

        assertThat(rule.validate(createKnowledgeBundleWith(markdownFile), markdownFile)).satisfiesOnlyOnce(issue -> {
            assertThat(issue.severity()).isEqualTo(ERROR);
            assertThat(issue.code()).isEqualTo(INVALID_GENERATED_AT);
            assertThat(issue.message()).isEqualTo("Invalid generated.at field in frontmatter - Not an ISO 8601 datetime format");
            assertThat(issue.path()).isEqualTo(markdownFilePath);
        });
    }

    @Test
    @DisplayName("Report missing verified by")
    void missingVerifiedBy() {
        var markdownFilePath = Path.of("concept-without-verified-by.md");
        var frontmatter = Frontmatter.builder()
                .type("Concept")
                .verified(List.of(TrustEvent.builder()
                        .at("2026-06-25T09:00:00Z")
                        .build()))
                .build();
        var markdownFile = createMarkdownFile(markdownFilePath, CONCEPT, frontmatter);

        assertThat(rule.validate(createKnowledgeBundleWith(markdownFile), markdownFile)).satisfiesOnlyOnce(issue -> {
            assertThat(issue.severity()).isEqualTo(ERROR);
            assertThat(issue.code()).isEqualTo(MISSING_VERIFIED_BY);
            assertThat(issue.message()).isEqualTo("Missing verified.by field in frontmatter for verified event");
            assertThat(issue.path()).isEqualTo(markdownFilePath);
        });
    }

    @Test
    @DisplayName("Report missing verified at")
    void missingVerifiedAt() {
        var markdownFilePath = Path.of("concept-without-verified-at.md");
        var frontmatter = Frontmatter.builder()
                .type("Concept")
                .verified(List.of(TrustEvent.builder()
                        .by(Actor.of("human:straumat"))
                        .build()))
                .build();
        var markdownFile = createMarkdownFile(markdownFilePath, CONCEPT, frontmatter);

        assertThat(rule.validate(createKnowledgeBundleWith(markdownFile), markdownFile)).satisfiesOnlyOnce(issue -> {
            assertThat(issue.severity()).isEqualTo(ERROR);
            assertThat(issue.code()).isEqualTo(MISSING_VERIFIED_AT);
            assertThat(issue.message()).isEqualTo("Missing verified.at field in frontmatter for verified event");
            assertThat(issue.path()).isEqualTo(markdownFilePath);
        });
    }

    @Test
    @DisplayName("Report invalid verified at")
    void invalidVerifiedAt() {
        var markdownFilePath = Path.of("concept-with-invalid-verified-at.md");
        var frontmatter = Frontmatter.builder()
                .type("Concept")
                .verified(List.of(TrustEvent.builder()
                        .by(Actor.of("human:straumat"))
                        .at("25-06-2026T09:00:00Z")
                        .build()))
                .build();
        var markdownFile = createMarkdownFile(markdownFilePath, CONCEPT, frontmatter);

        assertThat(rule.validate(createKnowledgeBundleWith(markdownFile), markdownFile)).satisfiesOnlyOnce(issue -> {
            assertThat(issue.severity()).isEqualTo(ERROR);
            assertThat(issue.code()).isEqualTo(INVALID_VERIFIED_AT);
            assertThat(issue.message()).isEqualTo("Invalid verified.at field in frontmatter - Not an ISO 8601 datetime format");
            assertThat(issue.path()).isEqualTo(markdownFilePath);
        });
    }

}
