name: Publish website

on:
  push:
    branches:
      - development
    paths:
      - "website/**"
      - ".github/workflows/publish-website.yml"

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: github-pages
  cancel-in-progress: true

jobs:
  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Set up environment
        uses: ./.github/actions/setup

      # Generate website examples ======================================================================================
      - name: Build kb-google-example with Kiso
        uses: oak-invest/kiso/applications/kiso-cli-action@v0.2.1
        with:
          command: build
          source: examples/kb-google-example-v0.2
          destination: website/examples/kb-google-example

      - name: Build kb-acme-example with Kiso
        uses: oak-invest/kiso/applications/kiso-cli-action@v0.2.1
        with:
          command: build
          source: examples/kb-acme-example-v0.2
          destination: website/examples/kb-acme-example

      # Publish the website to GitHub Pages ============================================================================
      - name: Configure GitHub Pages
        uses: actions/configure-pages@v6

      - name: Upload website
        uses: actions/upload-pages-artifact@v5
        with:
          path: website

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5